### ISSUE TITLE
Resolve Tanzania - Zanzibar problem 

### ISSUE THREAD

**Issue by DajanaSnopkova** [SLeitgeb/muni-international-students#4]
Incorrect country name in 50m dataset.

**Comment by SLeitgeb** [comment]
This is already resolved, see [50m_units.geojson](https://github.com/SLeitgeb/muni-international-students/blob/main/data/50m_units.geojson) and [10m_units.geojson](https://github.com/SLeitgeb/muni-international-students/blob/main/data/10m_units.geojson). Only [50m_units_students.geojson](https://github.com/SLeitgeb/muni-international-students/blob/main/data/50m_units_students.geojson) is built from the old version, and should be deleted soon anyway.
